---
title: "Preprocessing_2"
author: "KKawaguchi"
date: "2024-10-21"
output: html_document
---

# データを合算
# 手術・放射線治療・化学療法のいずれかが施行された症例のみを使用
```{r}
library(tidyverse)
library(tableone)
library(arrow)
```

# 各自治体データ読み込み
```{r}
df_1 <- read_parquet("your_directory/df_case_treated_1_LB12m_censor_main.parquet")
df_2 <- read_parquet("your_directory/df_case_treated_2_LB12m_censor_main.parquet")
df_3 <- read_parquet("your_directory/df_case_treated_3_LB12m_censor_main.parquet")
df_4 <- read_parquet("your_directory/df_case_treated_4_LB12m_censor_main.parquet")
df_5 <- read_parquet("your_directory/df_case_treated_5_LB12m_censor_main.parquet")
df_6 <- read_parquet("your_directory/df_case_treated_6_LB12m_censor_main.parquet")
df_7 <- read_parquet("your_directory/df_case_treated_7_LB12m_censor_main.parquet")
df_8 <- read_parquet("your_directory/df_case_treated_8_LB12m_censor_main.parquet")
df_9 <- read_parquet("your_directory/df_case_treated_9_LB12m_censor_main.parquet")
df_10 <- read_parquet("your_directory/df_case_treated_10_LB12m_censor_main.parquet")
df_11 <- read_parquet("your_directory/df_case_treated_11_LB12m_censor_main.parquet")
df_12 <- read_parquet("your_directory/df_case_treated_12_LB12m_censor_main.parquet")
df_13 <- read_parquet("your_directory/df_case_treated_13_LB12m_censor_main.parquet")
df_14 <- read_parquet("your_directory/df_case_treated_14_LB12m_censor_main.parquet")

df_all <- bind_rows(df_1, df_2, df_3, df_4, df_5, df_6, df_7, df_C8, df_9, df_10, df_11, df_12, df_13, df_14) 

# Date_last_followを作成：LF_24mかlmonの早い方
df_all <- df_all |> 
  mutate(Date_last_follow_depression = pmin(LF_24m, lmon, Date_event_depression, na.rm = TRUE)) |> 
  mutate(Date_last_follow_anxiety = pmin(LF_24m, lmon, Date_event_anxiety, na.rm = TRUE))
```

# 上皮内がんを除外
```{r}
df_all <- df_all |> 
  filter(!str_starts(icd1, "D")) 
```


# 診断後24か月のうつ病と不安障害の罹患率
```{r}
# うつ病
# 各患者のリスク期間（月単位）から総人月を算出
df_all <- df_all |> 
  mutate(risk_months_depression = interval(Date_entry, Date_last_follow_depression) %/% months(1))

person_months_depression <- sum(df_all$risk_months_depression)

# うつ病を発症した患者数をカウント
n_depression <- sum(df_all$Event_depression == 1 )

# 1000人月罹患率を算出
incidence_rate_depression <- n_depression / person_months_depression * 1000

print(paste("総人月:", person_months_depression)) 
print(paste("うつ病罹患率（1000人月）:", incidence_rate_depression)) 

# 不安障害
# 各患者のリスク期間（月単位）から総人月を算出
df_all <- df_all |> 
  mutate(risk_months_anxiety = interval(Date_entry, Date_last_follow_anxiety) %/% months(1))

person_months_anxiety <- sum(df_all$risk_months_anxiety)

# 不安障害を発症した患者数をカウント
n_anxiety <- sum(df_all$Event_anxiety == 1)

# 1000人月罹患率を算出
incidence_rate_anxiety <- n_anxiety / person_months_anxiety * 1000

print(paste("総人月:", person_months_anxiety)) 
print(paste("不安障害罹患率（1000人月）:", incidence_rate_anxiety)) 
```

# 性別ごとの罹患率
```{r}
# うつ病
incidence_rate_depression_gender <- df_all |> 
  group_by(sex) |> 
  summarise(person_months_depression = sum(risk_months_depression),
            n_depression = sum(Event_depression == 1),
            incidence_rate = n_depression / person_months_depression * 1000
            )

print(incidence_rate_depression_gender)

# 不安障害
incidence_rate_anxiety_gender <- df_all |> 
  group_by(sex) |> 
  summarise(person_months_anxiety = sum(risk_months_anxiety),
            n_anxiety = sum(Event_anxiety == 1),
            incidence_rate = n_anxiety / person_months_anxiety * 1000
            )

print(incidence_rate_anxiety_gender)
```

# 年齢ごとの罹患率（65歳未満 vs 65歳以上）
```{r}
# うつ病
df_all <- df_all |> 
  mutate(age_group = if_else(age >= 14, "1", "0"))

incidence_rate_depression_age <- df_all |> 
  group_by(age_group) |> 
  summarise(person_months_depression = sum(risk_months_depression),
            n_depression = sum(Event_depression == 1),
            incidence_rate = n_depression / person_months_depression * 1000
            )

print(incidence_rate_depression_age)

# 不安障害
incidence_rate_anxiety_age <- df_all |> 
  group_by(age_group) |> 
  summarise(person_months_anxiety = sum(risk_months_anxiety),
            n_anxiety = sum(Event_anxiety == 1),
            incidence_rate = n_anxiety / person_months_anxiety * 1000
            )

print(incidence_rate_anxiety_age)
```


# 手術の有無での罹患率
```{r}
# 固形がんに限定する（＝血液がんを除外する）
df_all_solidcancer <- df_all |> 
  filter(!str_starts(icd1, "^C81|^C81|^C83|^C84|^C85|^C86|^C96|^C88|^C90|^C91|^C92|^C93|^C94|^C95")) 

# うつ病
incidence_rate_depression_ope <- df_all_solidcancer |> 
  group_by(Ope) |> 
  summarise(person_months_depression = sum(risk_months_depression),
            n_depression = sum(Event_depression == 1),
            incidence_rate = n_depression / person_months_depression * 1000
            )

print(incidence_rate_depression_ope)


# 不安障害
incidence_rate_anxiety_ope <- df_all_solidcancer |> 
  group_by(Ope) |> 
  summarise(person_months_anxiety = sum(risk_months_anxiety),
            n_anxiety = sum(Event_anxiety == 1),
            incidence_rate = n_anxiety / person_months_anxiety * 1000
            )

print(incidence_rate_anxiety_ope)
```

# 放射線治療の有無での罹患率
```{r}
# 固形がんに限定する
# うつ病
incidence_rate_depression_RT <- df_all_solidcancer |> 
  group_by(Radiation) |> 
  summarise(person_months_depression = sum(risk_months_depression),
            n_depression = sum(Event_depression == 1),
            incidence_rate = n_depression / person_months_depression * 1000
            )

print(incidence_rate_depression_RT)

# 不安障害
incidence_rate_anxiety_RT <- df_all_solidcancer |> 
  group_by(Radiation) |> 
  summarise(person_months_anxiety = sum(risk_months_anxiety),
            n_anxiety = sum(Event_anxiety == 1),
            incidence_rate = n_anxiety / person_months_anxiety * 1000
            )

print(incidence_rate_anxiety_RT)
```

# 化学療法の有無での罹患率
```{r}
# うつ病
incidence_rate_depression_CT <- df_all |> 
  group_by(Chemotherapy) |> 
  summarise(person_months_depression = sum(risk_months_depression),
            n_depression = sum(Event_depression == 1),
            incidence_rate = n_depression / person_months_depression * 1000
            )

print(incidence_rate_depression_CT)

# 不安障害
incidence_rate_anxiety_CT <- df_all |> 
  group_by(Chemotherapy) |> 
  summarise(person_months_anxiety = sum(risk_months_anxiety),
            n_anxiety = sum(Event_anxiety == 1),
            incidence_rate = n_anxiety / person_months_anxiety * 1000
            )

print(incidence_rate_anxiety_CT)
```

# 詳細ながん種で検証
```{r}
df_all <- df_all |>
  mutate(Cancer_category_detail = case_when(
    str_starts(icd1, "^C0[0-9]|^C1[0-4]") ~ "Lip, oral cavity, and pharynx",
    str_starts(icd1, "^C15") ~ "Esophagus",
    str_starts(icd1, "^C16") ~ "Stomach",
    str_starts(icd1, "^C17") ~ "Small intestine",
    str_starts(icd1, "^C18|^C19|^C20|^C21") ~ "Colorectum",
    str_starts(icd1, "^C22") ~ "Liver",
    str_starts(icd1, "^C23|^C24") ~ "Gallbladder/biliary tract",
    str_starts(icd1, "^C25") ~ "Pancreas",
    str_starts(icd1, "^C26") ~ "Other digestive organs",
    str_starts(icd1, "^C30|^C31") ~ "Nasal cavity/sinus and middle ear",
    str_starts(icd1, "^C32") ~ "Larynx",
    str_starts(icd1, "^C33|^C34") ~ "Lung",
    str_starts(icd1, "^C37|^C38") ~ "Other intrathoracic organs",
    str_starts(icd1, "^C40|^C41") ~ "Bone and articular cartilage",
    str_starts(icd1, "^C43|^C44") ~ "Skin",
    str_starts(icd1, "^C45|^C46|^C47|^C48|^C49") ~ "Mesothelium and soft tissue",
    str_starts(icd1, "^C50") ~ "Breast",
    str_starts(icd1, "^C51|^C52|^C55|^C57|^C58") ~ "Other female genitalia",
    str_starts(icd1, "^C53") ~ "Uterine cervix",
    str_starts(icd1, "^C54") ~ "Uterine corpus",
    str_starts(icd1, "^C56") ~ "Ovary",
    str_starts(icd1, "^C61") ~ "Prostate",
    str_starts(icd1, "^C60|^C62|^C63") ~ "Other male genitalia",
    str_starts(icd1, "^C64|^C65|^C66|^C68") ~ "Kidney/urinary tract",
    str_starts(icd1, "^C67") ~ "Bladder",
    str_starts(icd1, "^C69") ~ "Eye",
    str_starts(icd1, "^C70|^C71|^C72") ~ "Brain/central nervous system",
    str_starts(icd1, "^C73") ~ "Thyroid gland",
    str_starts(icd1, "^C74|^C75") ~ "Other endocrine glands",
    str_starts(icd1, "^C76|^C77|^C78|^C79|^C80") ~ "Other malignant neoplasms",
    str_starts(icd1, "^C81|^C82|^C83|^C84|^C85|^C86|^C96") ~ "Malignant lymphoma",
    str_starts(icd1, "^C88|^C90") ~ "Multiple myeloma",
    str_starts(icd1, "^C91|^C92|^C93|^C94|^C95") ~ "Leukemia",
    str_starts(icd1, "^C97") ~ "Multiple categories",
    TRUE ~ "Other"
  ))

# がんカテゴリー別の集計
cancer_count_detail <- df_all |>
  count(Cancer_category_detail) |>
  arrange(desc(n))
print(cancer_count_detail)

# N>100の癌腫に限定
Main_cancer_type <- cancer_count_detail |> 
  filter(n >= 100)

df_all_mainsubtype_detail <- df_all |>
  filter(Cancer_category_detail %in% Main_cancer_type$Cancer_category_detail)

# うつ病(全がん)
incidence_rate_depression_cancertype_detail <- df_all |> 
  group_by(Cancer_category_detail) |> 
  summarise(person_months_depression = sum(risk_months_depression),
            n_depression = sum(Event_depression == 1),
            incidence_rate = n_depression / person_months_depression * 1000
            )

incidence_rate_depression_cancertype_detail |> arrange(desc(incidence_rate))

print(incidence_rate_depression_cancertype_detail)
write_csv(incidence_rate_depression_cancertype_detail, "incidence_rate_depression.csv")

ggplot(incidence_rate_depression_cancertype_detail, aes(x = reorder(Cancer_category_detail, incidence_rate), y = incidence_rate))+
  geom_bar(stat = "identity")+
  geom_text(aes(label = sprintf("%.2f", incidence_rate)), hjust = -0.2)+
  coord_flip()+
  theme(axis.text.y = element_text(size = 10),
        plot.background = element_rect(fill = "white", color= NA),
        panel.background = element_rect(fill = "white", color= NA))

# うつ病（N>100に限定）
incidence_rate_depression_cancertype_detail <- df_all_mainsubtype_detail |> 
  group_by(Cancer_category_detail) |> 
  summarise(person_months_depression = sum(risk_months_depression),
            n_depression = sum(Event_depression == 1),
            incidence_rate = n_depression / person_months_depression * 1000
            )

incidence_rate_depression_cancertype_detail |> arrange(desc(incidence_rate))

print(incidence_rate_depression_cancertype_detail)
write_csv(incidence_rate_depression_cancertype_detail, "incidence_rate_depression_maintype.csv")

ggplot(incidence_rate_depression_cancertype_detail, aes(x = reorder(Cancer_category_detail, incidence_rate), y = incidence_rate))+
  geom_bar(stat = "identity")+
  geom_text(aes(label = sprintf("%.2f", incidence_rate)), hjust = -0.2)+
  coord_flip()+
  theme(axis.text.y = element_text(size = 10),
        plot.background = element_rect(fill = "white", color= NA),
        panel.background = element_rect(fill = "white", color= NA))+
  labs(
    title = "",
    x = "",
    y = "Incidence rate of depression",
    color = "Type",
    fill = "Type"
  )

# 不安障害（全がん）
incidence_rate_anxiety_cancertype_detail <- df_all |> 
  group_by(Cancer_category_detail) |> 
  summarise(person_months_anxiety = sum(risk_months_anxiety),
            n_anxiety = sum(Event_anxiety == 1),
            incidence_rate = n_anxiety / person_months_anxiety * 1000
            )

incidence_rate_anxiety_cancertype_detail |> arrange(desc(incidence_rate))

print(incidence_rate_anxiety_cancertype_detail)

write_csv(incidence_rate_anxiety_cancertype_detail, "incidence_rate_anxiety.csv")

ggplot(incidence_rate_anxiety_cancertype_detail, aes(x = reorder(Cancer_category_detail, incidence_rate), y = incidence_rate))+
  geom_bar(stat = "identity")+
  geom_text(aes(label = sprintf("%.2f", incidence_rate)), hjust = -0.2)+
  coord_flip()+
  theme(axis.text.y = element_text(size = 10),
        plot.background = element_rect(fill = "white", color= NA),
        panel.background = element_rect(fill = "white", color= NA))  

# 不安障害（N>100のがんに限定）
incidence_rate_anxiety_cancertype_detail <- df_all_mainsubtype_detail |> 
  group_by(Cancer_category_detail) |> 
  summarise(person_months_anxiety = sum(risk_months_anxiety),
            n_anxiety = sum(Event_anxiety == 1),
            incidence_rate = n_anxiety / person_months_anxiety * 1000
            )

incidence_rate_anxiety_cancertype_detail |> arrange(desc(incidence_rate))

print(incidence_rate_anxiety_cancertype_detail)

write_csv(incidence_rate_anxiety_cancertype_detail, "incidence_rate_anxiety_maintype.csv")

ggplot(incidence_rate_anxiety_cancertype_detail, aes(x = reorder(Cancer_category_detail, incidence_rate), y = incidence_rate))+
  geom_bar(stat = "identity")+
  geom_text(aes(label = sprintf("%.2f", incidence_rate)), hjust = -0.2)+
  coord_flip()+
  theme(axis.text.y = element_text(size = 10),
        plot.background = element_rect(fill = "white", color= NA),
        panel.background = element_rect(fill = "white", color= NA))+
  labs(
    title = "",
    x = "",
    y = "Incidence rate of anxiety",
    color = "Type",
    fill = "Type"
  )
```

# 概算
```{r}
listvars <- c("sex", "age", "Cancer_category_detail",
              "Event_depression", "Event_anxiety",
              "Ope", "Radiation", "Chemotherapy") 

listcat <- c("sex", "age", "Cancer_category_detail",
              "Event_depression", "Event_anxiety",
              "Ope", "Radiation", "Chemotherapy")

Table1 <- CreateCatTable(vars = listcat,
                         addOverall = TRUE,
                         data = df_all)
print(Table1,
      showAllLevels = TRUE,
      explain = TRUE
      ) |> 
  write.csv("Tbale_1.csv")
```

```{r}
write_parquet(df_all, "df_all_LB12_main.parquet")
```

# 治療内容の分布を確認
```{r}
df_all <- read_parquet("df_all_LB12_main.parquet")

df_all$combination <- paste0("ope_", df_all$Ope, "_rad_", df_all$Radiation, "_chemo_", df_all$Chemotherapy)

results <- df_all |> 
  count(combination)

results$ratio <- results$n/22863*100 # 要追記

print(results)
```

# 各治療組み合わせ別の罹患率：うつ病
```{r}
incidence_rate_depression <- df_all |>
  group_by(combination) |> 
  summarise(person_months_depression = sum(risk_months_depression),
            n_depression = sum(Event_depression == 1),
            incidence_rate = n_depression / person_months_depression * 1000
            )

print(incidence_rate_depression)
```

# 各治療組み合わせ別の罹患率：不安障害
```{r}
incidence_rate_anxiety <- df_all |>
  group_by(combination) |> 
  summarise(person_months_anxiety = sum(risk_months_anxiety),
            n_anxiety = sum(Event_anxiety == 1),
            incidence_rate = n_anxiety / person_months_anxiety * 1000
            )

print(incidence_rate_anxiety)
```



