---
title: "Preprocessing_1"
author: "KKawaguchi"
date: "2024-09-12"
output: html_document
---
# 個別の自治体の処理
```{r}
library(tidyverse)
library(arrow)
library(skimr)
```

# 対象症例の抽出
```{r}
# 2018-2020年度のMED_SYOデータの読み込み
directory_path <- "your_directory"

files <- c("MED_SYO_201804_Mask.parquet",
           "MED_SYO_201805_Mask.parquet",
           "MED_SYO_201806_Mask.parquet",
           "MED_SYO_201807_Mask.parquet",
           "MED_SYO_201808_Mask.parquet",
           "MED_SYO_201809_Mask.parquet",
           "MED_SYO_201810_Mask.parquet",
           "MED_SYO_201811_Mask.parquet",
           "MED_SYO_201812_Mask.parquet",
           "MED_SYO_201901_Mask.parquet",
           "MED_SYO_201902_Mask.parquet",
           "MED_SYO_201903_Mask.parquet",
           "MED_SYO_201904_Mask.parquet",
           "MED_SYO_201905_Mask.parquet",
           "MED_SYO_201906_Mask.parquet",
           "MED_SYO_201907_Mask.parquet",
           "MED_SYO_201908_Mask.parquet",
           "MED_SYO_201909_Mask.parquet",
           "MED_SYO_201910_Mask.parquet",
           "MED_SYO_201911_Mask.parquet",
           "MED_SYO_201912_Mask.parquet",
           "MED_SYO_202001_Mask.parquet",
           "MED_SYO_202002_Mask.parquet",
           "MED_SYO_202003_Mask.parquet",
           "MED_SYO_202004_Mask.parquet",
           "MED_SYO_202005_Mask.parquet",
           "MED_SYO_202006_Mask.parquet",
           "MED_SYO_202007_Mask.parquet",
           "MED_SYO_202008_Mask.parquet",
           "MED_SYO_202009_Mask.parquet",
           "MED_SYO_202010_Mask.parquet",
           "MED_SYO_202011_Mask.parquet",
           "MED_SYO_202012_Mask.parquet",
           "MED_SYO_202101_Mask.parquet",
           "MED_SYO_202102_Mask.parquet",
           "MED_SYO_202103_Mask.parquet"
           )

file_path <- file.path(directory_path, files)

df_SYO_2018_2020 <- lapply(file_path, read_parquet) |>
  bind_rows() |>
  select(rtid2, sex, age, actdat, icd1, utagai) |>
  filter(!(utagai == "1"))|>
  select(-utagai)|>
  filter(grepl("^C[0-9][0-7]|^D0[0-9]", icd1))|> # がんのICD10が出現する行のみを抽出
  mutate(actdat = ymd(paste0(actdat, "01"))) # actdatをdate型に変更

# rtid2とicd1が同じ行は、actdatが早い行を残す
df_SYO_2018_2020 <- df_SYO_2018_2020|>
  group_by(rtid2, icd1)|>
  filter(actdat == min(actdat))|>
  ungroup()

# rtid2が欠損値の行を削除
df_SYO_2018_2020 <- df_SYO_2018_2020|>
  filter(!rtid2 == "_")

# rtid2の重複を削除
# ICD10コードの頭の数字が小さいものを採用
df_SYO_2018_2020 <- df_SYO_2018_2020|>
  group_by(rtid2)|>
  slice_min(order_by = icd1)|>
  ungroup() 

# rtid2とicd1が同一の行は、最初に出現した行を保持して重複を削除
df_SYO_2018_2020 <- df_SYO_2018_2020|>
  distinct(rtid2, icd1, .keep_all = TRUE)## この時点で重複なし
case_count_allpatient <- (df_SYO_2018_2020)

# 15歳未満を削除(年齢は5歳刻みのカテゴリー変数)
df_SYO_2018_2020 <- df_SYO_2018_2020|>
  filter(!age %in% c("01", "02", "03")) 
case_count_over15 <- (df_SYO_2018_2020)

# look backのために、actdatから12か月前の日付をLB_12mに格納
df_SYO_2018_2020 <- df_SYO_2018_2020|>
  mutate(LB_12m = actdat |> add_with_rollback(months(-12))) |>
  rename(Date_entry = actdat)

# 全期間（2017-2023年度）のMED_SYOデータの読み込み(2023年度は途中までの自治体あり)
directory_path <- "F:/Cancer_depression_research/MED/C001"
files <- list.files(path =directory_path, pattern = "MED_SYO.*\\.parquet$", full.names = TRUE)

df_SYO_allterm <- data.frame()

for (file in files){
  df_temp <- read_parquet(file)|>
    select(rtid2, actdat, icd1, utagai) |>
    filter(!(utagai == "1"))|>
    select(-utagai)|>
    mutate(actdat = ymd(paste0(actdat, "01")))
  
  df_SYO_allterm <- bind_rows(df_SYO_allterm, df_temp)
  
  #メモリ開放
  rm(df_temp)
  gc()
  
}

write_parquet(df_SYO_allterm, "df_SYO_allterm_C01.parquet")


# がんコードの行のみを抽出
icd_cancer <- c(paste0("C", sprintf("%02d", 0:97)), paste0("D", sprintf("%02d", 0:9)))
icd_cancer_pattern <- paste0("^(", paste(icd_cancer, collapse = "|"), ")")

df_SYO_cancer <- df_SYO_allterm |>
  filter(str_starts(icd1, icd_cancer_pattern))

# LB可能な症例のみを抽出するため、MED_KANを読み込む
directory_path <- "your_directory"
file_name <- "MED_KAN_Mask.parquet"

file_path <- file.path(directory_path, file_name)

df_KAN <- read_parquet(file_path) |>
  select(rtid2, fmon, lmon)

df_KAN$fmon <- as.Date(paste0(df_KAN$fmon, "01"), format = "%Y%m%d")
df_KAN$lmon <- as.Date(paste0(df_KAN$lmon, "01"), format = "%Y%m%d")

# fmonがLB_12m以降の症例（＝12mのLBができない症例）を除外
df_SYO_2018_2020 <- left_join(df_SYO_2018_2020, df_KAN, by = "rtid2")

df_SYO_2018_2020 <- df_SYO_2018_2020|>
  filter(fmon <= LB_12m) 
case_count_LBOK <- (df_SYO_2018_2020)

# 12ヵ月のlook back
Result_LB_cancer <- df_SYO_2018_2020 |>
  left_join(df_SYO_cancer, by = "rtid2") |>
  mutate(cancer_LB = ifelse(actdat >= LB_12m & actdat < Date_entry, 1, 0)) |>
  group_by(rtid2) |>
  mutate(cancer_LB = ifelse(is.na(cancer_LB), 0, cancer_LB)) |>
  summarize(cancer_LB = max(cancer_LB, na.rm=TRUE)) |>
  ungroup()

# LB結果列を結合し、LB期間にがん診断のある症例を除外
df_SYO_2018_2020 <- df_SYO_2018_2020 |>
  left_join(Result_LB_cancer, by = "rtid2") |>
  filter(cancer_LB == "0") 
case_count_LB_nonCancer <- (df_SYO_2018_2020)

# LBでうつ病（F31、F33）、恐怖性を除く不安障害（F41）が1回でも出現した症例を除外
# エントリー直前2か月より10ヶ月のLB
icd_depression <- c("F32", "F33", "F41")
icd_depression_pattern <- paste0("^(", paste(icd_depression, collapse = "|"), ")")

df_SYO_depression <- df_SYO_allterm |>
  filter(str_starts(icd1, icd_depression_pattern))

# 12ヵ月のlook back
Result_LB_depression <- df_SYO_2018_2020 |>
  left_join(df_SYO_depression, by = "rtid2") |>
  mutate(depression_LB = ifelse(actdat >= LB_12m & actdat < Date_entry, 1, 0)) |>
  group_by(rtid2) |>
  mutate(depression_LB = ifelse(is.na(depression_LB), 0, depression_LB)) |>
  summarize(depression_LB = max(depression_LB, na.rm=TRUE)) |>
  ungroup()

# LB結果列を結合し、LB期間にうつ病もしくは不安障害の診断のある症例を除外
df_SYO_2018_2020 <- df_SYO_2018_2020 |>
  left_join(Result_LB_depression, by = "rtid2") |>
  filter(depression_LB == "0")
case_count_LB_nonDepression <- (df_SYO_2018_2020)

# ここまでで、2018-2020年度の新規にがんと診断され、直近1年間でうつ病（+関連疾患）既往のない成人のデータが抽出完了
# 不要な行を削除
df_SYO_2018_2020 <- df_SYO_2018_2020|>
  select(-cancer_LB, -depression_LB, -fmon, -lmon)

# がん種類カテゴリー編集
df_SYO_2018_2020 <- df_SYO_2018_2020 |>
  mutate(Cancer_category = case_when(
    str_starts(icd1, "^C0[0-9]|^C1[0-4]") ~ "Malignant neoplasms of lip, oral cavity and pharynx",
    str_starts(icd1, "^C1[5-9]|^C2[0-6]") ~ "Malignant neoplasms of digestive organs",
    str_starts(icd1, "^C3[0-9]") ~ "Malignant neoplasms of respiratory and intrathoracic organs",
    str_starts(icd1, "^C4[0-1]") ~ "Malignant neoplasms of bone and articular cartilage",
    str_starts(icd1, "^C4[3-4]") ~ "Malignant neoplasms of skin",
    str_starts(icd1, "^C4[5-9]") ~ "Malignant neoplasms of mesothelial and soft tissue",
    str_starts(icd1, "^C50") ~ "Malignant neoplasms of breast",
    str_starts(icd1, "^C5[1-8]") ~ "Malignant neoplasms of female genital organs",
    str_starts(icd1, "^C6[0-3]") ~ "Malignant neoplasms of male genital organs",
    str_starts(icd1, "^C6[4-8]") ~ "Malignant neoplasms of urinary tract",
    str_starts(icd1, "^C69|^C7[0-2]") ~ "Malignant neoplasms of eye, brain and central nervous system",
    str_starts(icd1, "^C7[3-5]") ~ "Malignant neoplasms of thyroid and other endocrine glands",
    str_starts(icd1, "^C7[6-9]|^C80") ~ "Malignant neoplasms of ill-defined, secondary and unspecified sites",
    str_starts(icd1, "^C8[1-9]|^C9[0-6]") ~ "Malignant neoplasms of lymphoid, hematopoietic and related tissue",
    str_starts(icd1, "^C97") ~ "Malignant neoplasms of independent (primary) multiple sites",
    str_starts(icd1, "^D00") ~ "Intraepithelial carcinoma of the oral cavity, esophagus and stomach",
    str_starts(icd1, "^D01") ~ "Intraepithelial carcinoma of other or unspecified digestive organs",
    str_starts(icd1, "^D02") ~ "Intraepithelial carcinoma of the middle ear and respiratory system",
    str_starts(icd1, "^D03") ~ "Intraepithelial melanoma",
    str_starts(icd1, "^D04") ~ "Intraepithelial carcinoma of the skin",
    str_starts(icd1, "^D05") ~ "Intraepithelial carcinoma of the breast",
    str_starts(icd1, "^D06") ~ "Intraepithelial carcinoma of the cervix uteri",
    str_starts(icd1, "^D07") ~ "Intraepithelial carcinoma of other or unspecified organs",
    str_starts(icd1, "^D09") ~ "Intraepithelial carcinoma of other or unspecified sites",
    TRUE ~ "Other"
  ))

sum(duplicated(df_SYO_2018_2020$rtid2)) 

# がんカテゴリー別の集計
cancer_count <- df_SYO_2018_2020|>
  count(Cancer_category)|>
  arrange(desc(n))
print(cancer_count)

# rtid2の重複していないデータを保存
write_parquet(df_SYO_2018_2020, "Case_2018_2020.parquet") 
case_count_clear <- (df_SYO_2018_2020)
```

# イベント（うつ病、不安障害発症）の追加
```{r}
df_SYO_2018_2020 <- read_parquet("Case_2018_2020.parquet")
df_SYO_allterm <- read_parquet("df_SYO_allterm_C01.parquet")

# うつ病
icd_dep <- c("F32","F33")
icd_dep_pattern <- paste0("^(", paste(icd_dep, collapse = "|"), ")")

df_SYO_dep <- df_SYO_allterm |>
  filter(str_starts(icd1, icd_dep_pattern))|>
  filter(!is.na(actdat))|>
  filter(!rtid2=="_")

# 2年間のイベントを収集するため、Date_entryから24か月後の日付をLF_24mに格納
df_case <- df_SYO_2018_2020|>
  mutate(LF_24m = Date_entry |> add_with_rollback(months(24)))

# エントリー以降でイベントがあれば, Event_depression=1 なければ 0
# Event_depression=1の症例は、最初にうつ病の病名がついた日をDate_event_depressionに転記
Result_event_depression <- df_case |>
  left_join(df_SYO_dep, by = "rtid2") |>
  mutate(Event_depression = if_else(!is.na(actdat) & actdat >= Date_entry & actdat <= LF_24m, 1, 0)) |>
  group_by(rtid2) |>
  summarize(Event_depression = max(Event_depression, na.rm = TRUE),
            Date_event_depression = if_else(Event_depression == 1, min(actdat[actdat >= Date_entry], na.rm=TRUE), NA),
            ) |>
  ungroup()

df_case <- df_case |>
  left_join(Result_event_depression, by = "rtid2")

sum(df_case$Event_depression == 1) 

# 不安障害（恐怖症 phobic anxiety disorderは除く）
icd_anxiety <- c("F41")

df_SYO_anxiety <- df_SYO_allterm |>
  filter(str_starts(icd1, icd_anxiety))|>
  filter(!is.na(actdat))|>
  filter(!rtid2=="_")

# エントリー以降でイベントがあれば, Event_anxiety=1 なければ 0
# Event_anxiety=1の症例は、最初に病名がついた日をDate_event_anxietyに転記
Result_event_anxiety <- df_case |>
  left_join(df_SYO_anxiety, by = "rtid2") |>
  mutate(Event_anxiety = if_else(!is.na(actdat) & actdat >= Date_entry & actdat <= LF_24m, 1, 0)) |>
  group_by(rtid2) |>
  summarize(Event_anxiety = max(Event_anxiety, na.rm = TRUE),
            Date_event_anxiety = if_else(Event_anxiety == 1, min(actdat[actdat >= Date_entry], na.rm=TRUE), NA),
            ) |>
  ungroup()

df_case <- df_case |>
  left_join(Result_event_anxiety, by = "rtid2")

sum(df_case$Event_anxiety==1)

sum(df_case$Event_depression==1 | df_case$Event_anxiety==1) 
```

# 手術情報
```{r}
# MED_SINデータの読み込み
directory_path <- "your_directory"
files <- list.files(path =directory_path, pattern = "MED_SIN.*\\.parquet$", full.names = TRUE)

# 空の箱を作る
df_SIN <- data.frame()

# 格納していく
for (file in files){
  df_temp <-read_parquet(file)|>
    select(rtid2, actdat, sindai, sinkbn, sineda)|>
    filter(sindai == "K")
  
  df_SIN <- bind_rows(df_SIN, df_temp)
  
  rm(df_temp)
  gc()
}

# sinkbnとsinedaを"-"で連結してK_code列に格納
df_SIN$K_code <- paste(df_SIN$sinkbn, df_SIN$sineda, sep = "-")

# Date型に変換
df_SIN$actdat <- as.Date(paste0(df_SIN$actdat, "01"), format = "%Y%m%d")

# 切除術（内視鏡含む）のK code一覧
K_code_list <- read_csv("K_code_tumor_add.csv") # 20241213に、K721-00（大腸polypectomy）を追加
K_code_list <- K_code_list|>
  mutate(Code = gsub("K", "", K_code_tumor))|>
  select(-K_code_tumor)

# df_SINのうち、K_code列がK_code_listに含まれる行のみを抽出
df_SIN_ope <- df_SIN|>
  filter(K_code %in% K_code_list$Code)

# やや重い処理のため、書き出しておく
write_parquet(df_SIN_ope, "df_SIN_K_code_C01.parquet")


# 情報追加
df_SIN_ope <- read_parquet("df_SIN_K_code_C01.parquet")

df_SIN_ope <- df_SIN_ope|>
  select(rtid2, actdat, K_code)

# 1年間の手術情報を収集するため、Date_entryから12か月後の日付をLF_12mに格納
df_case <- df_case|>
  mutate(LF_12m = Date_entry |> add_with_rollback(months(12)))

# エントリー以降でOpeがあれば, Ope=1 なければ 0
# Ope=1の症例は、最初にOpe日をDate_opeに転記
Result_ope <- df_case |>
  left_join(df_SIN_ope, by = "rtid2") |>
  filter(!is.na(actdat) & actdat >= Date_entry & actdat <= LF_12m)|>
  group_by(rtid2) |>
  summarise(Ope = 1,
            Date_ope = min(actdat, na.rm = TRUE),
            Surgical_procedure = K_code[which.min(actdat)]
            )|>
  ungroup()

df_case <- df_case|>
  left_join(Result_ope, by = "rtid2")|>
  mutate(Ope = if_else(is.na(Ope), 0, Ope))

sum(df_case$Ope==1) 

write_parquet(df_case, "df_case_ope.parquet")
```

# 放射線照射
```{r}
df_case_ope <- read_parquet("df_case_ope.parquet")

# MED_SINデータの読み込み
directory_path <- "your_directory"
files <- list.files(path =directory_path, pattern = "MED_SIN.*\\.parquet$", full.names = TRUE)

df_SIN_Mcode <- data.frame()

for (file in files){
  df_temp <-read_parquet(file)|>
    select(rtid2, actdat, sindai, sinkbn)|>
    filter(sindai == "M") # Mコードが出現した時点で放射線治療が施行されており、枝番は不要
  
  df_SIN_Mcode <- bind_rows(df_SIN_Mcode, df_temp)
  
  rm(df_temp)
  gc()
}

# Date型に変換
df_SIN_Mcode$actdat <- as.Date(paste0(df_SIN_Mcode$actdat, "01"), format = "%Y%m%d")

# 情報追加
# M code=000（管理料）のみ除外：照射のみにする
df_SIN_Mcode <- df_SIN_Mcode|>
  filter(!(sinkbn == "000"))

# エントリー以降でradiationがあれば, radiation=1 なければ 0
# radiation=1の症例は、最初のrariation日をDate_radiationに転記
Result_radi <- df_case_ope |>
  left_join(df_SIN_Mcode, by = "rtid2") |>
  mutate(Radiation = if_else(!is.na(actdat) & actdat >= Date_entry & actdat <= LF_12m, 1, 0)) |>
  group_by(rtid2) |>
  summarize(Radiation = max(Radiation, na.rm = TRUE),
            Date_radiation = if_else(Radiation == 1, min(actdat[actdat >= Date_entry], na.rm=TRUE), NA),
            ) |>
  ungroup()

df_case_ope <- df_case_ope |>
  left_join(Result_radi, by = "rtid2")

sum(df_case_ope$Radiation==1) 

write_parquet(df_case_ope, "df_case_radi.parquet")
```

# 化学療法
```{r}
df_case_radi <- read_parquet("df_case_radi.parquet")

# 化学療法薬一覧
anticancer_drugs <- read_csv("Anti_cancer_drugs.csv", locale = locale(encoding = "CP932"))
anticancer_drugs <- anticancer_drugs|>
  select(code)

# 情報追加
# df_IYAのうち、化学療法コードの行のみを抽出
# C01では、ここも重すぎて処理できず、修正
dataset <- open_dataset("df_IYA_C01.parquet")

df_IYA_anticancer <- dataset|>
  filter(drcod %in% anticancer_drugs$code)|>
  collect()

# エントリー以降で抗がん剤投与があれば, chemotherapy=1 なければ 0
# chemotherapy=1の症例は、最初のchemotherapy日をDate_chemotherapyに転記
Result_chemo <- df_case_radi |>
  left_join(df_IYA_anticancer, by = "rtid2") |>
  mutate(Chemotherapy = if_else(!is.na(actdat) & actdat >= Date_entry & actdat <= LF_12m, 1, 0)) |>
  group_by(rtid2) |>
  summarize(Chemotherapy = max(Chemotherapy, na.rm = TRUE),
            Date_chemotherapy = if_else(Chemotherapy == 1, min(actdat[actdat >= Date_entry], na.rm=TRUE), NA),
            ) |>
  ungroup()

df_case_radi <- df_case_radi |>
  left_join(Result_chemo, by = "rtid2")

sum(df_case_radi$Chemotherapy==1) 

write_parquet(df_case_radi, "df_case_chemo.parquet")

# ここまでで、手術・放射線治療・化学療法の情報が取得できた
```

# 確認
```{r}
df_case_chemo <- read_parquet("df_case_chemo.parquet")

# 診断から1年以内に手術・放射線治療・化学療法のいずれかが施行された症例を抽出
df_case_treated <- df_case_chemo|>
  filter(Ope==1 | Radiation==1 | Chemotherapy==1)
case_count_treated <- (df_case_treated)

table(df_case_treated$age)
df_case_treated$age <- as.numeric(df_case_treated$age)
hist(df_case_treated$age)
```

# 何らかの治療が行われた症例のみを使用する
# うつ病・不安障害発症
```{r}
# うつ病
sum(df_case_treated$Event_depression == 1) 
# 不安障害
sum(df_case_treated$Event_anxiety == 1) 
# いずれかを発症
sum(df_case_treated$Event_depression == 1 | df_case_treated$Event_anxiety == 1) 

write_parquet(df_case_treated, "df_case_treated_LB12m.parquet") 
```

# 最終レセプト発生日の情報を追加
```{r}
#df_case_treated <- read_parquet("df_case_treated_LB12m.parquet")

# LB可能な症例のみを抽出するため、MED_KANを読み込む
directory_path <- "your_directory"
file_name <- "MED_KAN_Mask.parquet"

file_path <- file.path(directory_path, file_name)

df_KAN <- read_parquet(file_path) |>
  select(rtid2, lmon)

df_KAN$lmon <- as.Date(paste0(df_KAN$lmon, "01"), format = "%Y%m%d")

df_case_treated <- df_case_treated |> 
  left_join(df_KAN, by = "rtid2")

write_parquet(df_case_treated, "df_case_treated_1_LB12m_censor_main.parquet")
```